//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.NavigationPane {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tobi_Plugin_NavigationPane_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tobi_Plugin_NavigationPane_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobi.Plugin.NavigationPane.Tobi.Plugin.NavigationPane.Lang", typeof(Tobi_Plugin_NavigationPane_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Navigation pane.
        /// </summary>
        public static string CmdNavigationFocus_ShortDesc {
            get {
                return ResourceManager.GetString("CmdNavigationFocus_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch off the marks in the entire document.
        /// </summary>
        public static string CmdNavigationRemoveAllMarks_LongDesc {
            get {
                return ResourceManager.GetString("CmdNavigationRemoveAllMarks_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove all document marks.
        /// </summary>
        public static string CmdNavigationRemoveAllMarks_ShortDesc {
            get {
                return ResourceManager.GetString("CmdNavigationRemoveAllMarks_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch on/off the marker on the currently-selected text item.
        /// </summary>
        public static string CmdNavigationToggleMark_LongDesc {
            get {
                return ResourceManager.GetString("CmdNavigationToggleMark_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Toggle document mark.
        /// </summary>
        public static string CmdNavigationToggleMark_ShortDesc {
            get {
                return ResourceManager.GetString("CmdNavigationToggleMark_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all children in the tree.
        /// </summary>
        public static string CmdTreeCollapseAll_LongDesc {
            get {
                return ResourceManager.GetString("CmdTreeCollapseAll_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Collapse all.
        /// </summary>
        public static string CmdTreeCollapseAll_ShortDesc {
            get {
                return ResourceManager.GetString("CmdTreeCollapseAll_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all children in the tree.
        /// </summary>
        public static string CmdTreeExpandAll_LongDesc {
            get {
                return ResourceManager.GetString("CmdTreeExpandAll_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xpand all.
        /// </summary>
        public static string CmdTreeExpandAll_ShortDesc {
            get {
                return ResourceManager.GetString("CmdTreeExpandAll_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find:.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Heading.
        /// </summary>
        public static string HeadingEdit {
            get {
                return ResourceManager.GetString("HeadingEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter The New Value For This Heading..
        /// </summary>
        public static string HeadingEdit_ {
            get {
                return ResourceManager.GetString("HeadingEdit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Navigation panel.
        /// </summary>
        public static string HeadingNavigationPlugin_Description {
            get {
                return ResourceManager.GetString("HeadingNavigationPlugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation pane..
        /// </summary>
        public static string HeadingNavigationPlugin_Name {
            get {
                return ResourceManager.GetString("HeadingNavigationPlugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headings.
        /// </summary>
        public static string Headings {
            get {
                return ResourceManager.GetString("Headings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked.
        /// </summary>
        public static string Marked {
            get {
                return ResourceManager.GetString("Marked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The markers navigation plugin.
        /// </summary>
        public static string MarkersNavigationPlugin_Description {
            get {
                return ResourceManager.GetString("MarkersNavigationPlugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markers navigation plugin.
        /// </summary>
        public static string MarkersNavigationPlugin_Name {
            get {
                return ResourceManager.GetString("MarkersNavigationPlugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks.
        /// </summary>
        public static string Marks {
            get {
                return ResourceManager.GetString("Marks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document _marks.
        /// </summary>
        public static string Menu_Markers {
            get {
                return ResourceManager.GetString("Menu_Markers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Navigation panel.
        /// </summary>
        public static string NavigationPanePlugin_Description {
            get {
                return ResourceManager.GetString("NavigationPanePlugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation pane..
        /// </summary>
        public static string NavigationPanePlugin_Name {
            get {
                return ResourceManager.GetString("NavigationPanePlugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No heading).
        /// </summary>
        public static string NoHeading {
            get {
                return ResourceManager.GetString("NoHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string PageFindNext {
            get {
                return ResourceManager.GetString("PageFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the next matching item in the page list.
        /// </summary>
        public static string PageFindNext_ {
            get {
                return ResourceManager.GetString("PageFindNext_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No More Matches Found.
        /// </summary>
        public static string PageFindNext_FAILURE {
            get {
                return ResourceManager.GetString("PageFindNext_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Previous.
        /// </summary>
        public static string PageFindPrev {
            get {
                return ResourceManager.GetString("PageFindPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the previous matching item in the page list.
        /// </summary>
        public static string PageFindPrev_ {
            get {
                return ResourceManager.GetString("PageFindPrev_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No More Matches Found.
        /// </summary>
        public static string PageFindPrev_FAILURE {
            get {
                return ResourceManager.GetString("PageFindPrev_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page navigation plugin.
        /// </summary>
        public static string PageNavigationPlugin_Description {
            get {
                return ResourceManager.GetString("PageNavigationPlugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page navigation plugin.
        /// </summary>
        public static string PageNavigationPlugin_Name {
            get {
                return ResourceManager.GetString("PageNavigationPlugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all.
        /// </summary>
        public static string RemoveAllMarkers {
            get {
                return ResourceManager.GetString("RemoveAllMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co_llapse.
        /// </summary>
        public static string TreeCollapse {
            get {
                return ResourceManager.GetString("TreeCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse the current item in the tree.
        /// </summary>
        public static string TreeCollapse_ {
            get {
                return ResourceManager.GetString("TreeCollapse_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit _Heading.
        /// </summary>
        public static string TreeEdit {
            get {
                return ResourceManager.GetString("TreeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the current heading.
        /// </summary>
        public static string TreeEdit_ {
            get {
                return ResourceManager.GetString("TreeEdit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex_pand.
        /// </summary>
        public static string TreeExpand {
            get {
                return ResourceManager.GetString("TreeExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand the current item in the tree.
        /// </summary>
        public static string TreeExpand_ {
            get {
                return ResourceManager.GetString("TreeExpand_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string TreeFindNext {
            get {
                return ResourceManager.GetString("TreeFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the next matching item in the tree.
        /// </summary>
        public static string TreeFindNext_ {
            get {
                return ResourceManager.GetString("TreeFindNext_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No More Matches Found.
        /// </summary>
        public static string TreeFindNext_FAILURE {
            get {
                return ResourceManager.GetString("TreeFindNext_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Previous.
        /// </summary>
        public static string TreeFindPrev {
            get {
                return ResourceManager.GetString("TreeFindPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the previous matching item in the tree.
        /// </summary>
        public static string TreeFindPrev_ {
            get {
                return ResourceManager.GetString("TreeFindPrev_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No More Matches Found.
        /// </summary>
        public static string TreeFindPrev_FAILURE {
            get {
                return ResourceManager.GetString("TreeFindPrev_FAILURE", resourceCulture);
            }
        }
    }
}
