//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.Validator.MissingAudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tobi_Plugin_Validator_MissingAudio_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tobi_Plugin_Validator_MissingAudio_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobi.Plugin.Validator.MissingAudio.Tobi.Plugin.Validator.MissingAudio.Lang", typeof(Tobi_Plugin_Validator_MissingAudio_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to view.
        /// </summary>
        public static string ClickToView {
            get {
                return ResourceManager.GetString("ClickToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing audio content.
        /// </summary>
        public static string MissingAudio {
            get {
                return ResourceManager.GetString("MissingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &lt;{0}&gt; is missing audio.
        /// </summary>
        public static string MissingAudioMessage {
            get {
                return ResourceManager.GetString("MissingAudioMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element &lt;{0}&gt; has no associated audio content..
        /// </summary>
        public static string MissingAudioMessage2 {
            get {
                return ResourceManager.GetString("MissingAudioMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing audio content
        ///The element &lt;{0}&gt; has no associated audio content.
        ///{1}.
        /// </summary>
        public static string MissingAudioSummary {
            get {
                return ResourceManager.GetString("MissingAudioSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports text content that has no associated audio.
        /// </summary>
        public static string MissingAudioValidator_Description {
            get {
                return ResourceManager.GetString("MissingAudioValidator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing audio.
        /// </summary>
        public static string MissingAudioValidator_Name {
            get {
                return ResourceManager.GetString("MissingAudioValidator_Name", resourceCulture);
            }
        }
    }
}
