//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.AudioPane {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings_KeyGestures : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_KeyGestures defaultInstance = ((Settings_KeyGestures)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_KeyGestures())));
        
        public static Settings_KeyGestures Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_Focus_KEYS {
            get {
                return ((string)(this["Audio_Focus_KEYS"]));
            }
            set {
                this["Audio_Focus_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_FocusStatusBar_KEYS {
            get {
                return ((string)(this["Audio_FocusStatusBar_KEYS"]));
            }
            set {
                this["Audio_FocusStatusBar_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_BeginSelection_KEYS {
            get {
                return ((string)(this["Audio_BeginSelection_KEYS"]));
            }
            set {
                this["Audio_BeginSelection_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_EndSelection_KEYS {
            get {
                return ((string)(this["Audio_EndSelection_KEYS"]));
            }
            set {
                this["Audio_EndSelection_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_Delete_KEYS {
            get {
                return ((string)(this["Audio_Delete_KEYS"]));
            }
            set {
                this["Audio_Delete_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_InsertFile_KEYS {
            get {
                return ((string)(this["Audio_InsertFile_KEYS"]));
            }
            set {
                this["Audio_InsertFile_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_OpenFile_KEYS {
            get {
                return ((string)(this["Audio_OpenFile_KEYS"]));
            }
            set {
                this["Audio_OpenFile_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_GotoBegin_KEYS {
            get {
                return ((string)(this["Audio_GotoBegin_KEYS"]));
            }
            set {
                this["Audio_GotoBegin_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_GotoEnd_KEYS {
            get {
                return ((string)(this["Audio_GotoEnd_KEYS"]));
            }
            set {
                this["Audio_GotoEnd_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_SelectPreviousChunk_KEYS {
            get {
                return ((string)(this["Audio_SelectPreviousChunk_KEYS"]));
            }
            set {
                this["Audio_SelectPreviousChunk_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_SelectNextChunk_KEYS {
            get {
                return ((string)(this["Audio_SelectNextChunk_KEYS"]));
            }
            set {
                this["Audio_SelectNextChunk_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_StepBack_KEYS {
            get {
                return ((string)(this["Audio_StepBack_KEYS"]));
            }
            set {
                this["Audio_StepBack_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_StepForward_KEYS {
            get {
                return ((string)(this["Audio_StepForward_KEYS"]));
            }
            set {
                this["Audio_StepForward_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_FastForward_KEYS {
            get {
                return ((string)(this["Audio_FastForward_KEYS"]));
            }
            set {
                this["Audio_FastForward_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_Rewind_KEYS {
            get {
                return ((string)(this["Audio_Rewind_KEYS"]));
            }
            set {
                this["Audio_Rewind_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_ClearSelection_KEYS {
            get {
                return ((string)(this["Audio_ClearSelection_KEYS"]));
            }
            set {
                this["Audio_ClearSelection_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_ZoomSelection_KEYS {
            get {
                return ((string)(this["Audio_ZoomSelection_KEYS"]));
            }
            set {
                this["Audio_ZoomSelection_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_FitFull_KEYS {
            get {
                return ((string)(this["Audio_FitFull_KEYS"]));
            }
            set {
                this["Audio_FitFull_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_AutoPlay_KEYS {
            get {
                return ((string)(this["Audio_AutoPlay_KEYS"]));
            }
            set {
                this["Audio_AutoPlay_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_StartRecord_KEYS {
            get {
                return ((string)(this["Audio_StartRecord_KEYS"]));
            }
            set {
                this["Audio_StartRecord_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_StopRecord_KEYS {
            get {
                return ((string)(this["Audio_StopRecord_KEYS"]));
            }
            set {
                this["Audio_StopRecord_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_StartMonitor_KEYS {
            get {
                return ((string)(this["Audio_StartMonitor_KEYS"]));
            }
            set {
                this["Audio_StartMonitor_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_StopMonitor_KEYS {
            get {
                return ((string)(this["Audio_StopMonitor_KEYS"]));
            }
            set {
                this["Audio_StopMonitor_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_Play_KEYS {
            get {
                return ((string)(this["Audio_Play_KEYS"]));
            }
            set {
                this["Audio_Play_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_PlayPreviewLeft_KEYS {
            get {
                return ((string)(this["Audio_PlayPreviewLeft_KEYS"]));
            }
            set {
                this["Audio_PlayPreviewLeft_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_PlayPreviewRight_KEYS {
            get {
                return ((string)(this["Audio_PlayPreviewRight_KEYS"]));
            }
            set {
                this["Audio_PlayPreviewRight_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_Pause_KEYS {
            get {
                return ((string)(this["Audio_Pause_KEYS"]));
            }
            set {
                this["Audio_Pause_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Audio_ShowOptions_KEYS {
            get {
                return ((string)(this["Audio_ShowOptions_KEYS"]));
            }
            set {
                this["Audio_ShowOptions_KEYS"] = value;
            }
        }
    }
}
