//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.AudioPane {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tobi_Plugin_AudioPane_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tobi_Plugin_AudioPane_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobi.Plugin.AudioPane.Tobi.Plugin.AudioPane.Lang", typeof(Tobi_Plugin_AudioPane_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St_art recording.
        /// </summary>
        public static string Audio_StartRecord {
            get {
                return ResourceManager.GetString("Audio_StartRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording audio.
        /// </summary>
        public static string Audio_StartRecord_ {
            get {
                return ResourceManager.GetString("Audio_StartRecord_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio waveform zoom.
        /// </summary>
        public static string Audio_ZoomSlider {
            get {
                return ResourceManager.GetString("Audio_ZoomSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audio waveform editor and display..
        /// </summary>
        public static string AudioPanePlugin_Description {
            get {
                return ResourceManager.GetString("AudioPanePlugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio waveform editor..
        /// </summary>
        public static string AudioPanePlugin_Name {
            get {
                return ResourceManager.GetString("AudioPanePlugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch autoplay on/off.
        /// </summary>
        public static string CmdAudioAutoPlay_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioAutoPlay_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Toggle autoplay.
        /// </summary>
        public static string CmdAudioAutoPlay_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioAutoPlay_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin audio waveform selection.
        /// </summary>
        public static string CmdAudioBeginSelection_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioBeginSelection_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Begin selection.
        /// </summary>
        public static string CmdAudioBeginSelection_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioBeginSelection_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the current audio selection.
        /// </summary>
        public static string CmdAudioClearSelection_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioClearSelection_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear selection.
        /// </summary>
        public static string CmdAudioClearSelection_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioClearSelection_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the audio in the waveform selection.
        /// </summary>
        public static string CmdAudioDelete_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioDelete_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete audio selection.
        /// </summary>
        public static string CmdAudioDelete_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioDelete_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End audio waveform selection.
        /// </summary>
        public static string CmdAudioEndSelection_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioEndSelection_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _End selection.
        /// </summary>
        public static string CmdAudioEndSelection_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioEndSelection_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump forward by a pre-defined time increment.
        /// </summary>
        public static string CmdAudioFastForward_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioFastForward_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Step forward.
        /// </summary>
        public static string CmdAudioFastForward_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioFastForward_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit the entire audio waveform into view.
        /// </summary>
        public static string CmdAudioFitFull_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioFitFull_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Fit into view.
        /// </summary>
        public static string CmdAudioFitFull_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioFitFull_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio pane focus.
        /// </summary>
        public static string CmdAudioFocus_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioFocus_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status bar focus.
        /// </summary>
        public static string CmdAudioFocusStatusBar_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioFocusStatusBar_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind to the begining of the audio stream.
        /// </summary>
        public static string CmdAudioGotoBegin_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioGotoBegin_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Go to begin.
        /// </summary>
        public static string CmdAudioGotoBegin_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioGotoBegin_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Forward to the end of the audio stream.
        /// </summary>
        public static string CmdAudioGotoEnd_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioGotoEnd_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Go to end.
        /// </summary>
        public static string CmdAudioGotoEnd_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioGotoEnd_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a local WAV or MP3 file.
        /// </summary>
        public static string CmdAudioInsertFile_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioInsertFile_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Insert audio file.
        /// </summary>
        public static string CmdAudioInsertFile_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioInsertFile_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a local WAV or MP3.
        /// </summary>
        public static string CmdAudioOpenFile_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioOpenFile_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open audio file.
        /// </summary>
        public static string CmdAudioOpenFile_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioOpenFile_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause playback.
        /// </summary>
        public static string CmdAudioPause_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioPause_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Pause.
        /// </summary>
        public static string CmdAudioPause_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioPause_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start playback.
        /// </summary>
        public static string CmdAudioPlay_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioPlay_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pla_y.
        /// </summary>
        public static string CmdAudioPlay_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioPlay_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview the audio just before the current cursor position.
        /// </summary>
        public static string CmdAudioPlayPreviewLeft_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioPlayPreviewLeft_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview _before.
        /// </summary>
        public static string CmdAudioPlayPreviewLeft_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioPlayPreviewLeft_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview the audio right after the current cursor position.
        /// </summary>
        public static string CmdAudioPlayPreviewRight_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioPlayPreviewRight_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview _after.
        /// </summary>
        public static string CmdAudioPlayPreviewRight_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioPlayPreviewRight_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the playback speed down.
        /// </summary>
        public static string CmdAudioPlayRateDown_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioPlayRateDown_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Descrease playback rate.
        /// </summary>
        public static string CmdAudioPlayRateDown_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioPlayRateDown_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the normal playback speed.
        /// </summary>
        public static string CmdAudioPlayRateReset_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioPlayRateReset_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset playback rate.
        /// </summary>
        public static string CmdAudioPlayRateReset_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioPlayRateReset_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the playback speed up.
        /// </summary>
        public static string CmdAudioPlayRateUp_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioPlayRateUp_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Increase playback rate.
        /// </summary>
        public static string CmdAudioPlayRateUp_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioPlayRateUp_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload the audio waveform data.
        /// </summary>
        public static string CmdAudioReload_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioReload_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reload audio.
        /// </summary>
        public static string CmdAudioReload_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioReload_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump back by a pre-defined time increment.
        /// </summary>
        public static string CmdAudioRewind_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioRewind_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Step backwards.
        /// </summary>
        public static string CmdAudioRewind_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioRewind_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the entire audio phrase following the current one.
        /// </summary>
        public static string CmdAudioSelectNextChunk_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioSelectNextChunk_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select next phrase.
        /// </summary>
        public static string CmdAudioSelectNextChunk_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioSelectNextChunk_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the entire audio phrase preceding the current one.
        /// </summary>
        public static string CmdAudioSelectPreviousChunk_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioSelectPreviousChunk_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select previous phrase.
        /// </summary>
        public static string CmdAudioSelectPreviousChunk_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioSelectPreviousChunk_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for the audio player and recorder.
        /// </summary>
        public static string CmdAudioSettings_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioSettings_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio se_ttings.
        /// </summary>
        public static string CmdAudioSettings_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioSettings_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show audio options.
        /// </summary>
        public static string CmdAudioShowOptions_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioShowOptions_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start monitoring audio input.
        /// </summary>
        public static string CmdAudioStartMonitor_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioStartMonitor_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St_art monitoring.
        /// </summary>
        public static string CmdAudioStartMonitor_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioStartMonitor_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step back one phrase.
        /// </summary>
        public static string CmdAudioStepBack_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioStepBack_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Back one phrase.
        /// </summary>
        public static string CmdAudioStepBack_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioStepBack_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step forward one phrase.
        /// </summary>
        public static string CmdAudioStepForward_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioStepForward_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Forward one phrase.
        /// </summary>
        public static string CmdAudioStepForward_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioStepForward_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the audio input monitoring.
        /// </summary>
        public static string CmdAudioStopMonitor_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioStopMonitor_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St_op monitoring.
        /// </summary>
        public static string CmdAudioStopMonitor_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioStopMonitor_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the current recording.
        /// </summary>
        public static string CmdAudioStopRecord_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioStopRecord_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St_op recording.
        /// </summary>
        public static string CmdAudioStopRecord_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioStopRecord_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom waveform selection into view.
        /// </summary>
        public static string CmdAudioZoomSelection_LongDesc {
            get {
                return ResourceManager.GetString("CmdAudioZoomSelection_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zoom on selection.
        /// </summary>
        public static string CmdAudioZoomSelection_ShortDesc {
            get {
                return ResourceManager.GetString("CmdAudioZoomSelection_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CmdCopy_LongDesc {
            get {
                return ResourceManager.GetString("CmdCopy_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string CmdCopy_ShortDesc {
            get {
                return ResourceManager.GetString("CmdCopy_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut to clipboard.
        /// </summary>
        public static string CmdCut_LongDesc {
            get {
                return ResourceManager.GetString("CmdCut_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_ut.
        /// </summary>
        public static string CmdCut_ShortDesc {
            get {
                return ResourceManager.GetString("CmdCut_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from clipboard.
        /// </summary>
        public static string CmdPaste_LongDesc {
            get {
                return ResourceManager.GetString("CmdPaste_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string CmdPaste_ShortDesc {
            get {
                return ResourceManager.GetString("CmdPaste_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all content.
        /// </summary>
        public static string CmdSelectAll_LongDesc {
            get {
                return ResourceManager.GetString("CmdSelectAll_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Select all.
        /// </summary>
        public static string CmdSelectAll_ShortDesc {
            get {
                return ResourceManager.GetString("CmdSelectAll_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete spanning audio portion.
        /// </summary>
        public static string CmdTransaction_DeleteAudio {
            get {
                return ResourceManager.GetString("CmdTransaction_DeleteAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a portion of audio that spans across several treenodes.
        /// </summary>
        public static string CmdTransaction_DeleteAudioInSeveraTreenodes {
            get {
                return ResourceManager.GetString("CmdTransaction_DeleteAudioInSeveraTreenodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback:.
        /// </summary>
        public static string ComboLabel_Playback {
            get {
                return ResourceManager.GetString("ComboLabel_Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording:.
        /// </summary>
        public static string ComboLabel_Recording {
            get {
                return ResourceManager.GetString("ComboLabel_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading (ESC to stop).
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading waveform....
        /// </summary>
        public static string LoadingWaveform {
            get {
                return ResourceManager.GetString("LoadingWaveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring....
        /// </summary>
        public static string Monitoring {
            get {
                return ResourceManager.GetString("Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring stopped..
        /// </summary>
        public static string MonitoringStopped {
            get {
                return ResourceManager.GetString("MonitoringStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document.
        /// </summary>
        public static string NoDocument {
            get {
                return ResourceManager.GetString("NoDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback ended..
        /// </summary>
        public static string PlaybackEnded {
            get {
                return ResourceManager.GetString("PlaybackEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback stopped..
        /// </summary>
        public static string PlaybackStopped {
            get {
                return ResourceManager.GetString("PlaybackStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback x{0}.
        /// </summary>
        public static string PlaybackX {
            get {
                return ResourceManager.GetString("PlaybackX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing....
        /// </summary>
        public static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording....
        /// </summary>
        public static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording stopped..
        /// </summary>
        public static string RecordingStopped {
            get {
                return ResourceManager.GetString("RecordingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waveform loaded..
        /// </summary>
        public static string WaveformLoaded {
            get {
                return ResourceManager.GetString("WaveformLoaded", resourceCulture);
            }
        }
    }
}
