//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tobi_Plugin_Settings_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tobi_Plugin_Settings_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobi.Plugin.Settings.Tobi.Plugin.Settings.Lang", typeof(Tobi_Plugin_Settings_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application preferences.
        /// </summary>
        public static string Cmd_ApplicationPref {
            get {
                return ResourceManager.GetString("Cmd_ApplicationPref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display an editor for application preferences.
        /// </summary>
        public static string Cmd_DisplayEditor {
            get {
                return ResourceManager.GetString("Cmd_DisplayEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find:.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid keyboard shortcut..
        /// </summary>
        public static string InvalidKeyboardShortcut {
            get {
                return ResourceManager.GetString("InvalidKeyboardShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid numeric value..
        /// </summary>
        public static string InvalidNumericValue {
            get {
                return ResourceManager.GetString("InvalidNumericValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric value is out of range [0, 9999]..
        /// </summary>
        public static string NumericValueOutOfRange {
            get {
                return ResourceManager.GetString("NumericValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric value is out of range [-9999, 9999]..
        /// </summary>
        public static string NumericValueOutOfRange9999 {
            get {
                return ResourceManager.GetString("NumericValueOutOfRange9999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application configurable options.
        /// </summary>
        public static string Preferences_ {
            get {
                return ResourceManager.GetString("Preferences_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original: {0}.
        /// </summary>
        public static string Settings_OriginalValue {
            get {
                return ResourceManager.GetString("Settings_OriginalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A manager and user-interface editor for application preferences..
        /// </summary>
        public static string SettingsPlugin_Description {
            get {
                return ResourceManager.GetString("SettingsPlugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application preferences..
        /// </summary>
        public static string SettingsPlugin_Name {
            get {
                return ResourceManager.GetString("SettingsPlugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut already used by: {0}.
        /// </summary>
        public static string ShortcutAlreadyUsed {
            get {
                return ResourceManager.GetString("ShortcutAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be empty..
        /// </summary>
        public static string StringCannotBeEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot just be separators (e.g. space characters)..
        /// </summary>
        public static string StringCannotJustBeSeparators {
            get {
                return ResourceManager.GetString("StringCannotJustBeSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty..
        /// </summary>
        public static string ValueNotEmpty {
            get {
                return ResourceManager.GetString("ValueNotEmpty", resourceCulture);
            }
        }
    }
}
