//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.Descriptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tobi_Plugin_Descriptions_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tobi_Plugin_Descriptions_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobi.Plugin.Descriptions.Tobi.Plugin.Descriptions.Lang", typeof(Tobi_Plugin_Descriptions_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / edit ....
        /// </summary>
        public static string AddEdit {
            get {
                return ResourceManager.GetString("AddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative images.
        /// </summary>
        public static string AlternativeImages {
            get {
                return ResourceManager.GetString("AlternativeImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attribute already exists..
        /// </summary>
        public static string AttributeAlreadyExists {
            get {
                return ResourceManager.GetString("AttributeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/edit....
        /// </summary>
        public static string AudioAddEdit {
            get {
                return ResourceManager.GetString("AudioAddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string AudioClear {
            get {
                return ResourceManager.GetString("AudioClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio (click to edit).
        /// </summary>
        public static string AudioIcon {
            get {
                return ResourceManager.GetString("AudioIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string AudioPlay {
            get {
                return ResourceManager.GetString("AudioPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically rename linked identifiers?\n(recommended).
        /// </summary>
        public static string AutomaticallyID {
            get {
                return ResourceManager.GetString("AutomaticallyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the description(s) of the selected document item.
        /// </summary>
        public static string CmdEditDescriptions_LongDesc {
            get {
                return ResourceManager.GetString("CmdEditDescriptions_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit image _description.
        /// </summary>
        public static string CmdEditDescriptions_ShortDesc {
            get {
                return ResourceManager.GetString("CmdEditDescriptions_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions.
        /// </summary>
        public static string Descriptions {
            get {
                return ResourceManager.GetString("Descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user-interface to edit image descriptions..
        /// </summary>
        public static string DescriptionsPlugin_Description {
            get {
                return ResourceManager.GetString("DescriptionsPlugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions editor..
        /// </summary>
        public static string DescriptionsPlugin_Name {
            get {
                return ResourceManager.GetString("DescriptionsPlugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIAGRAM element name.
        /// </summary>
        public static string DIAGRAMElementName {
            get {
                return ResourceManager.GetString("DIAGRAMElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Invalid syntax for DIAGRAM elements: .
        /// </summary>
        public static string DiagramElementsInvalidSyntax {
            get {
                return ResourceManager.GetString("DiagramElementsInvalidSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Unknown DIAGRAM elements:.
        /// </summary>
        public static string DiagramUnknownElements {
            get {
                return ResourceManager.GetString("DiagramUnknownElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate attribute!.
        /// </summary>
        public static string DuplicateAttribute {
            get {
                return ResourceManager.GetString("DuplicateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Some identifiers are duplicated (this may be valid if used for grouping objects):.
        /// </summary>
        public static string DuplicatedIDs {
            get {
                return ResourceManager.GetString("DuplicatedIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit in advanced mode....
        /// </summary>
        public static string EditAdvanced {
            get {
                return ResourceManager.GetString("EditAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit attribute.
        /// </summary>
        public static string EditAttribute {
            get {
                return ResourceManager.GetString("EditAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit description text.
        /// </summary>
        public static string EditDescriptionText {
            get {
                return ResourceManager.GetString("EditDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [enter text here].
        /// </summary>
        public static string EnterTextPlaceholder {
            get {
                return ResourceManager.GetString("EnterTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show empty alt.
        /// </summary>
        public static string FilterEmptyAlt {
            get {
                return ResourceManager.GetString("FilterEmptyAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first select an image to describe..
        /// </summary>
        public static string FirstSelectImage {
            get {
                return ResourceManager.GetString("FirstSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Some dates seem invalid:.
        /// </summary>
        public static string InvalidDates {
            get {
                return ResourceManager.GetString("InvalidDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Some identifiers are invalid:.
        /// </summary>
        public static string InvalidIDs {
            get {
                return ResourceManager.GetString("InvalidIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Some language tags are invalid:.
        /// </summary>
        public static string InvalidLanguageTags {
            get {
                return ResourceManager.GetString("InvalidLanguageTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (has other data).
        /// </summary>
        public static string LongDescHasOtherData {
            get {
                return ResourceManager.GetString("LongDescHasOtherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (has other data, see advanced editor).
        /// </summary>
        public static string LongDescHasOtherDataAdvanced {
            get {
                return ResourceManager.GetString("LongDescHasOtherDataAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - No long description is specified..
        /// </summary>
        public static string LongDescMissing {
            get {
                return ResourceManager.GetString("LongDescMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - There are more than one long description.
        /// </summary>
        public static string LongDescMoreThanOne {
            get {
                return ResourceManager.GetString("LongDescMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The long description shouldn&apos;t have an image..
        /// </summary>
        public static string LongDescNoImage {
            get {
                return ResourceManager.GetString("LongDescNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long description.
        /// </summary>
        public static string LongDescription {
            get {
                return ResourceManager.GetString("LongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The long description provides the primary description of the associated image, graphic or visually-oriented structure. It should therefore contain a comprehensive explanation of the referenced item. See the summary description for information on how to include a compact description..
        /// </summary>
        public static string LongDescriptionHelp {
            get {
                return ResourceManager.GetString("LongDescriptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The long description text is missing..
        /// </summary>
        public static string LongDescTextMissing {
            get {
                return ResourceManager.GetString("LongDescTextMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Some identifiers are referenced, but are missing:.
        /// </summary>
        public static string MissingIDs {
            get {
                return ResourceManager.GetString("MissingIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio (click to edit).
        /// </summary>
        public static string NoAudioIcon {
            get {
                return ResourceManager.GetString("NoAudioIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No issues detected..
        /// </summary>
        public static string NoIssues {
            get {
                return ResourceManager.GetString("NoIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open DIAGRAM XML file.
        /// </summary>
        public static string OpenDiagramXml {
            get {
                return ResourceManager.GetString("OpenDiagramXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open image.
        /// </summary>
        public static string OpenImage {
            get {
                return ResourceManager.GetString("OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor identifiers?.
        /// </summary>
        public static string RefactorIdentifiers {
            get {
                return ResourceManager.GetString("RefactorIdentifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The simplified language description provides a simplified version of the primary long description..
        /// </summary>
        public static string SimplifiedDescriptionHelp {
            get {
                return ResourceManager.GetString("SimplifiedDescriptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified image.
        /// </summary>
        public static string SimplifiedImage {
            get {
                return ResourceManager.GetString("SimplifiedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The simplified image has audio but no corresponding tour..
        /// </summary>
        public static string SimplifiedImageAudioNoTour {
            get {
                return ResourceManager.GetString("SimplifiedImageAudioNoTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to which will be grouped if they have the same identifier and share the same tour..
        /// </summary>
        public static string SimplifiedImageGroupID {
            get {
                return ResourceManager.GetString("SimplifiedImageGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The simplified image provides a simplified version of the source image, optionally associated with an explanatory tour. Using the advanced editor, it is possible to specify one or more identical simplified images, in different formats..
        /// </summary>
        public static string SimplifiedImageHelp {
            get {
                return ResourceManager.GetString("SimplifiedImageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The simplified image is missing..
        /// </summary>
        public static string SimplifiedImageMissing {
            get {
                return ResourceManager.GetString("SimplifiedImageMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Image is missing for simplified image..
        /// </summary>
        public static string SimplifiedImageMissingImage {
            get {
                return ResourceManager.GetString("SimplifiedImageMissingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - There are more than one simplified image.
        /// </summary>
        public static string SimplifiedImageMoreThanOne {
            get {
                return ResourceManager.GetString("SimplifiedImageMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Tour text is recommended for simplified image..
        /// </summary>
        public static string SimplifiedImageTourRecommended {
            get {
                return ResourceManager.GetString("SimplifiedImageTourRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified language.
        /// </summary>
        public static string SimplifiedLanguage {
            get {
                return ResourceManager.GetString("SimplifiedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - There are more than one simplified language.
        /// </summary>
        public static string SimplifiedLanguageMoreThanOne {
            get {
                return ResourceManager.GetString("SimplifiedLanguageMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The simplified language shouldn&apos;t have an image..
        /// </summary>
        public static string SimplifiedLanguageNoImage {
            get {
                return ResourceManager.GetString("SimplifiedLanguageNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The simplified language text is missing..
        /// </summary>
        public static string SimplifiedLanguageTextMissing {
            get {
                return ResourceManager.GetString("SimplifiedLanguageTextMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summary description provides a shorter, more succinct version of the primary long description..
        /// </summary>
        public static string SummaryDescriptionHelp {
            get {
                return ResourceManager.GetString("SummaryDescriptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - There are more than one summary.
        /// </summary>
        public static string SummaryMoreThanOne {
            get {
                return ResourceManager.GetString("SummaryMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The summary shouldn&apos;t have an image..
        /// </summary>
        public static string SummaryNoImage {
            get {
                return ResourceManager.GetString("SummaryNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The summary text is missing..
        /// </summary>
        public static string SummaryTextMissing {
            get {
                return ResourceManager.GetString("SummaryTextMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to advanced editor.
        /// </summary>
        public static string SwitchToAdvancedEditor {
            get {
                return ResourceManager.GetString("SwitchToAdvancedEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to basic editor.
        /// </summary>
        public static string SwitchToBasicEditor {
            get {
                return ResourceManager.GetString("SwitchToBasicEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tactile image.
        /// </summary>
        public static string TactileImage {
            get {
                return ResourceManager.GetString("TactileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The tactile image has audio but no corresponding tour..
        /// </summary>
        public static string TactileImageAudioNoTour {
            get {
                return ResourceManager.GetString("TactileImageAudioNoTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tactile image provides an alternative image to the source image, optionally associated with an explanatory tour. Using the advanced editor, it is possible to specify one or more identical tactile images for different production methods, differentiated by their role attribute (e.g., one for swell paper production and another for stereolithograph printing)..
        /// </summary>
        public static string TactileImageHelp {
            get {
                return ResourceManager.GetString("TactileImageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The tactile image is missing..
        /// </summary>
        public static string TactileImageMissing {
            get {
                return ResourceManager.GetString("TactileImageMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Image is missing for tactile image..
        /// </summary>
        public static string TactileImageMissingImage {
            get {
                return ResourceManager.GetString("TactileImageMissingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - There are more than one tactile image.
        /// </summary>
        public static string TactileImageMoreThanOne {
            get {
                return ResourceManager.GetString("TactileImageMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Tour text is recommended for tactile image..
        /// </summary>
        public static string TactileImageTourRecommended {
            get {
                return ResourceManager.GetString("TactileImageTourRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text descriptions.
        /// </summary>
        public static string TextDescriptions {
            get {
                return ResourceManager.GetString("TextDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        public static string Tour {
            get {
                return ResourceManager.GetString("Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tour description associated with a tactile graphic or a simplified alternative image provides orientation, and explains how to conceptually explore the images..
        /// </summary>
        public static string TourHelp {
            get {
                return ResourceManager.GetString("TourHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
