//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.DocumentPane {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00FFFF")]
        public global::System.Windows.Media.Color Document_Color_Hyperlink_Back {
            get {
                return ((global::System.Windows.Media.Color)(this["Document_Color_Hyperlink_Back"]));
            }
            set {
                this["Document_Color_Hyperlink_Back"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFDDCCDD")]
        public global::System.Windows.Media.Color Document_Color_TextOnly_Back {
            get {
                return ((global::System.Windows.Media.Color)(this["Document_Color_TextOnly_Back"]));
            }
            set {
                this["Document_Color_TextOnly_Back"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Document_Highlight_TextOnly_Fragments {
            get {
                return ((bool)(this["Document_Highlight_TextOnly_Fragments"]));
            }
            set {
                this["Document_Highlight_TextOnly_Fragments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFDCDCDC")]
        public global::System.Windows.Media.Color Document_Color_PageNum_Back {
            get {
                return ((global::System.Windows.Media.Color)(this["Document_Color_PageNum_Back"]));
            }
            set {
                this["Document_Color_PageNum_Back"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color Document_Back {
            get {
                return ((global::System.Windows.Media.Color)(this["Document_Back"]));
            }
            set {
                this["Document_Back"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman")]
        public global::System.Windows.Media.FontFamily Document_TypeFace {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["Document_TypeFace"]));
            }
            set {
                this["Document_TypeFace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public double Document_Zoom {
            get {
                return ((double)(this["Document_Zoom"]));
            }
            set {
                this["Document_Zoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Document_EnableInstantSearch {
            get {
                return ((bool)(this["Document_EnableInstantSearch"]));
            }
            set {
                this["Document_EnableInstantSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Document_UseDottedSelect {
            get {
                return ((bool)(this["Document_UseDottedSelect"]));
            }
            set {
                this["Document_UseDottedSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Document_SinglePhraseView {
            get {
                return ((bool)(this["Document_SinglePhraseView"]));
            }
            set {
                this["Document_SinglePhraseView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public global::System.Windows.TextAlignment Document_TextOnlyAlign {
            get {
                return ((global::System.Windows.TextAlignment)(this["Document_TextOnlyAlign"]));
            }
            set {
                this["Document_TextOnlyAlign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Document_ButtonBarVisible {
            get {
                return ((bool)(this["Document_ButtonBarVisible"]));
            }
            set {
                this["Document_ButtonBarVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color Document_Color_Font_Audio {
            get {
                return ((global::System.Windows.Media.Color)(this["Document_Color_Font_Audio"]));
            }
            set {
                this["Document_Color_Font_Audio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color Document_Color_Font_TextOnly {
            get {
                return ((global::System.Windows.Media.Color)(this["Document_Color_Font_TextOnly"]));
            }
            set {
                this["Document_Color_Font_TextOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF686868")]
        public global::System.Windows.Media.Color Document_Color_Font_NoAudio {
            get {
                return ((global::System.Windows.Media.Color)(this["Document_Color_Font_NoAudio"]));
            }
            set {
                this["Document_Color_Font_NoAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00FF00")]
        public global::System.Windows.Media.Color Document_Color_Selection_UnderOverLine {
            get {
                return ((global::System.Windows.Media.Color)(this["Document_Color_Selection_UnderOverLine"]));
            }
            set {
                this["Document_Color_Selection_UnderOverLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color Document_Color_Selection_Font {
            get {
                return ((global::System.Windows.Media.Color)(this["Document_Color_Selection_Font"]));
            }
            set {
                this["Document_Color_Selection_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF6B8E23")]
        public global::System.Windows.Media.Color Document_Color_Selection_Border {
            get {
                return ((global::System.Windows.Media.Color)(this["Document_Color_Selection_Border"]));
            }
            set {
                this["Document_Color_Selection_Border"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF5F5F5")]
        public global::System.Windows.Media.Color Document_Color_Selection_Back1 {
            get {
                return ((global::System.Windows.Media.Color)(this["Document_Color_Selection_Back1"]));
            }
            set {
                this["Document_Color_Selection_Back1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF98FB98")]
        public global::System.Windows.Media.Color Document_Color_Selection_Back2 {
            get {
                return ((global::System.Windows.Media.Color)(this["Document_Color_Selection_Back2"]));
            }
            set {
                this["Document_Color_Selection_Back2"] = value;
            }
        }
    }
}
