//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.DocumentPane {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tobi_Plugin_DocumentPane_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tobi_Plugin_DocumentPane_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobi.Plugin.DocumentPane.Tobi.Plugin.DocumentPane.Lang", typeof(Tobi_Plugin_DocumentPane_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the text of the selected document phrase.
        /// </summary>
        public static string CmdEditText_LongDesc {
            get {
                return ResourceManager.GetString("CmdEditText_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit _text.
        /// </summary>
        public static string CmdEditText_ShortDesc {
            get {
                return ResourceManager.GetString("CmdEditText_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the next text fragment in the document.
        /// </summary>
        public static string CmdEventSwitchNext_LongDesc {
            get {
                return ResourceManager.GetString("CmdEventSwitchNext_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _next phrase.
        /// </summary>
        public static string CmdEventSwitchNext_ShortDesc {
            get {
                return ResourceManager.GetString("CmdEventSwitchNext_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the previous text fragment in the document.
        /// </summary>
        public static string CmdEventSwitchPrevious_LongDesc {
            get {
                return ResourceManager.GetString("CmdEventSwitchPrevious_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _previous phrase.
        /// </summary>
        public static string CmdEventSwitchPrevious_ShortDesc {
            get {
                return ResourceManager.GetString("CmdEventSwitchPrevious_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow the hyperlink in the document.
        /// </summary>
        public static string CmdFollowLink_LongDesc {
            get {
                return ResourceManager.GetString("CmdFollowLink_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Follow link.
        /// </summary>
        public static string CmdFollowLink_ShortDesc {
            get {
                return ResourceManager.GetString("CmdFollowLink_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a copy of the selected document fragment into the structure clipboard.
        /// </summary>
        public static string CmdStructEditCopyFragment_LongDesc {
            get {
                return ResourceManager.GetString("CmdStructEditCopyFragment_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy fragment.
        /// </summary>
        public static string CmdStructEditCopyFragment_ShortDesc {
            get {
                return ResourceManager.GetString("CmdStructEditCopyFragment_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected document fragment, and preserve in structure clipboard.
        /// </summary>
        public static string CmdStructEditCutFragment_LongDesc {
            get {
                return ResourceManager.GetString("CmdStructEditCutFragment_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut fragment.
        /// </summary>
        public static string CmdStructEditCutFragment_ShortDesc {
            get {
                return ResourceManager.GetString("CmdStructEditCutFragment_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add basic XML markup (element name + text content).
        /// </summary>
        public static string CmdStructEditInsertFragment_LongDesc {
            get {
                return ResourceManager.GetString("CmdStructEditInsertFragment_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert custom XML... (advanced feature).
        /// </summary>
        public static string CmdStructEditInsertFragment_ShortDesc {
            get {
                return ResourceManager.GetString("CmdStructEditInsertFragment_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a numbered page break into the document.
        /// </summary>
        public static string CmdStructEditInsertPageBreak_LongDesc {
            get {
                return ResourceManager.GetString("CmdStructEditInsertPageBreak_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert page break ....
        /// </summary>
        public static string CmdStructEditInsertPageBreak_ShortDesc {
            get {
                return ResourceManager.GetString("CmdStructEditInsertPageBreak_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the document fragment from the structure clipboard into the document.
        /// </summary>
        public static string CmdStructEditPasteFragment_LongDesc {
            get {
                return ResourceManager.GetString("CmdStructEditPasteFragment_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste fragment ....
        /// </summary>
        public static string CmdStructEditPasteFragment_ShortDesc {
            get {
                return ResourceManager.GetString("CmdStructEditPasteFragment_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected fragment from the document.
        /// </summary>
        public static string CmdStructEditRemoveFragment_LongDesc {
            get {
                return ResourceManager.GetString("CmdStructEditRemoveFragment_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete fragment.
        /// </summary>
        public static string CmdStructEditRemoveFragment_ShortDesc {
            get {
                return ResourceManager.GetString("CmdStructEditRemoveFragment_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract the selection down one level in the document structure.
        /// </summary>
        public static string CmdStructureDown_LongDesc {
            get {
                return ResourceManager.GetString("CmdStructureDown_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narro_w selection.
        /// </summary>
        public static string CmdStructureDown_ShortDesc {
            get {
                return ResourceManager.GetString("CmdStructureDown_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grow the selection up one level in the document structure.
        /// </summary>
        public static string CmdStructureUp_LongDesc {
            get {
                return ResourceManager.GetString("CmdStructureUp_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xpand selection.
        /// </summary>
        public static string CmdStructureUp_ShortDesc {
            get {
                return ResourceManager.GetString("CmdStructureUp_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open / close the audio narration popup window.
        /// </summary>
        public static string CmdSwitchNarratorView_LongDesc {
            get {
                return ResourceManager.GetString("CmdSwitchNarratorView_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Narrator window.
        /// </summary>
        public static string CmdSwitchNarratorView_ShortDesc {
            get {
                return ResourceManager.GetString("CmdSwitchNarratorView_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the text viewer mode.
        /// </summary>
        public static string CmdTextOnlyViewToggle_LongDesc {
            get {
                return ResourceManager.GetString("CmdTextOnlyViewToggle_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Single text phrase.
        /// </summary>
        public static string CmdTextOnlyViewToggle_ShortDesc {
            get {
                return ResourceManager.GetString("CmdTextOnlyViewToggle_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Document toolbar.
        /// </summary>
        public static string CmdTxtFocus_ShortDesc {
            get {
                return ResourceManager.GetString("CmdTxtFocus_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump back to the hyperlink that points to the current location in the document.
        /// </summary>
        public static string CmdUnfollowLink_LongDesc {
            get {
                return ResourceManager.GetString("CmdUnfollowLink_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Go back to link.
        /// </summary>
        public static string CmdUnfollowLink_ShortDesc {
            get {
                return ResourceManager.GetString("CmdUnfollowLink_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to overwrite the existing structure clipboard?.
        /// </summary>
        public static string ConfirmStructureClipboard {
            get {
                return ResourceManager.GetString("ConfirmStructureClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting XUK markup ....
        /// </summary>
        public static string ConvertingXukToFlowDocument {
            get {
                return ResourceManager.GetString("ConvertingXukToFlowDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering the document ....
        /// </summary>
        public static string CreatingFlowDocument {
            get {
                return ResourceManager.GetString("CreatingFlowDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publication document viewer.
        /// </summary>
        public static string DocumentPanePlugin_Description {
            get {
                return ResourceManager.GetString("DocumentPanePlugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document pane..
        /// </summary>
        public static string DocumentPanePlugin_Name {
            get {
                return ResourceManager.GetString("DocumentPanePlugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element name.
        /// </summary>
        public static string ElementName {
            get {
                return ResourceManager.GetString("ElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not available..
        /// </summary>
        public static string Feature_Not_Available {
            get {
                return ResourceManager.GetString("Feature_Not_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string InsertDocFragmentAfter {
            get {
                return ResourceManager.GetString("InsertDocFragmentAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string InsertDocFragmentBefore {
            get {
                return ResourceManager.GetString("InsertDocFragmentBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First inside.
        /// </summary>
        public static string InsertDocFragmentFirstInside {
            get {
                return ResourceManager.GetString("InsertDocFragmentFirstInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last inside.
        /// </summary>
        public static string InsertDocFragmentLastInside {
            get {
                return ResourceManager.GetString("InsertDocFragmentLastInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0].
        /// </summary>
        public static string LOG_FILE_PATH {
            get {
                return ResourceManager.GetString("LOG_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: MathML will display during selection.
        /// </summary>
        public static string MathMLSelectToShow {
            get {
                return ResourceManager.GetString("MathMLSelectToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrator view.
        /// </summary>
        public static string NarratorView {
            get {
                return ResourceManager.GetString("NarratorView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document..
        /// </summary>
        public static string No_Document {
            get {
                return ResourceManager.GetString("No_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page label (number).
        /// </summary>
        public static string PageLabel {
            get {
                return ResourceManager.GetString("PageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (note that this message is displayed only once per project session).
        /// </summary>
        public static string StructEditConfirmDetails {
            get {
                return ResourceManager.GetString("StructEditConfirmDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you aware of the implications when editing the structure of the document? This is currently an experimental feature that requires cautious use, because it modifies the XML markup of the document without automatically checking for syntax errors (DAISY DTBOOK / EPUB3 XHTML5). Please make sure that structural modifications do not create an invalid document!.
        /// </summary>
        public static string StructEditConfirmMessage {
            get {
                return ResourceManager.GetString("StructEditConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure editing warning!.
        /// </summary>
        public static string StructEditConfirmTitle {
            get {
                return ResourceManager.GetString("StructEditConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text content.
        /// </summary>
        public static string TextContent {
            get {
                return ResourceManager.GetString("TextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single phrase.
        /// </summary>
        public static string TextOnly {
            get {
                return ResourceManager.GetString("TextOnly", resourceCulture);
            }
        }
    }
}
