//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.MetadataPane {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tobi_Plugin_MetadataPane_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tobi_Plugin_MetadataPane_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobi.Plugin.MetadataPane.Tobi.Plugin.MetadataPane.Lang", typeof(Tobi_Plugin_MetadataPane_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new metadata item.
        /// </summary>
        public static string Add_new {
            get {
                return ResourceManager.GetString("Add_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata viewer/editor.
        /// </summary>
        public static string CmdShowMetadata_LongDesc {
            get {
                return ResourceManager.GetString("CmdShowMetadata_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit metadata.
        /// </summary>
        public static string CmdShowMetadata_ShortDesc {
            get {
                return ResourceManager.GetString("CmdShowMetadata_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this item.
        /// </summary>
        public static string Delete_Tooltip {
            get {
                return ResourceManager.GetString("Delete_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete required item (unless there are duplicates).
        /// </summary>
        public static string Delete_Tooltip2 {
            get {
                return ResourceManager.GetString("Delete_Tooltip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurrence:.
        /// </summary>
        public static string Metadata_Occurence {
            get {
                return ResourceManager.GetString("Metadata_Occurence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publication metadata editor.
        /// </summary>
        public static string MetadataPanePlugin_Description {
            get {
                return ResourceManager.GetString("MetadataPanePlugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata editor panel.
        /// </summary>
        public static string MetadataPanePlugin_Name {
            get {
                return ResourceManager.GetString("MetadataPanePlugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string PrimaryIdentifier {
            get {
                return ResourceManager.GetString("PrimaryIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        public static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of errors.
        /// </summary>
        public static string SummaryOfErrors {
            get {
                return ResourceManager.GetString("SummaryOfErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonyms: {0}.
        /// </summary>
        public static string Synonyms {
            get {
                return ResourceManager.GetString("Synonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata edits.
        /// </summary>
        public static string TransactionMetadataEdit_LongDesc {
            get {
                return ResourceManager.GetString("TransactionMetadataEdit_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata editor.
        /// </summary>
        public static string TransactionMetadataEdit_ShortDesc {
            get {
                return ResourceManager.GetString("TransactionMetadataEdit_ShortDesc", resourceCulture);
            }
        }
    }
}
