//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.MetadataPane {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tobi_Plugin_MetadataPane_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tobi_Plugin_MetadataPane_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobi.Plugin.MetadataPane.Tobi.Plugin.MetadataPane.Lang", typeof(Tobi_Plugin_MetadataPane_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata editor modal dialog is opening..
        /// </summary>
        public static string DialogOpen {
            get {
                return ResourceManager.GetString("DialogOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata editor panel..
        /// </summary>
        public static string MetadataEditorPanel {
            get {
                return ResourceManager.GetString("MetadataEditorPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open metadata editor.
        /// </summary>
        public static string OpenMetadataEditor {
            get {
                return ResourceManager.GetString("OpenMetadataEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional..
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publication metadata editor.
        /// </summary>
        public static string PublicationMetadataEditor {
            get {
                return ResourceManager.GetString("PublicationMetadataEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended..
        /// </summary>
        public static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit metadata.
        /// </summary>
        public static string ShowMetadata {
            get {
                return ResourceManager.GetString("ShowMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata viewer/editor.
        /// </summary>
        public static string ShowMetadata_ {
            get {
                return ResourceManager.GetString("ShowMetadata_", resourceCulture);
            }
        }
    }
}
