//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.Validator.ContentDocument {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tobi_Plugin_Validator_ContentDocument_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tobi_Plugin_Validator_ContentDocument_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobi.Plugin.Validator.ContentDocument.Tobi.Plugin.Validator.ContentDocument.Lang", typeof(Tobi_Plugin_Validator_ContentDocument_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobi could not locate a DTD, so it cannot validate the document..
        /// </summary>
        public static string CannotValidateDoc {
            get {
                return ResourceManager.GetString("CannotValidateDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to view.
        /// </summary>
        public static string ClickToView {
            get {
                return ResourceManager.GetString("ClickToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifies the validity of the text document.
        /// </summary>
        public static string ContentDocumentValidator_Description {
            get {
                return ResourceManager.GetString("ContentDocumentValidator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markup errors.
        /// </summary>
        public static string ContentDocumentValidator_Name {
            get {
                return ResourceManager.GetString("ContentDocumentValidator_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element definition was not found for:.
        /// </summary>
        public static string DefinitionNotFound {
            get {
                return ResourceManager.GetString("DefinitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DTD identifier associated with this document:.
        /// </summary>
        public static string DTDIdentifier {
            get {
                return ResourceManager.GetString("DTDIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid element sequence.
        /// </summary>
        public static string InvalidElementSequence {
            get {
                return ResourceManager.GetString("InvalidElementSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element &lt;{0}&gt; contains an invalid sequence of child elements.
        /// </summary>
        public static string InvalidElementSequenceMessage {
            get {
                return ResourceManager.GetString("InvalidElementSequenceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Element Sequence
        ///Element &lt;{0}&gt; contains an invalid sequence of child elements.
        ///{1}
        ///The following are permitted as children for &lt;{0}&gt;:
        ///{2}.
        /// </summary>
        public static string InvalidElementSequenceSummary {
            get {
                return ResourceManager.GetString("InvalidElementSequenceSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing DTD.
        /// </summary>
        public static string MissingDTD {
            get {
                return ResourceManager.GetString("MissingDTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing DTD
        ///Tobi could not locate a DTD, so it cannot validate the document.
        ///The DTD identifier associated with this document is:
        ///{0}.
        /// </summary>
        public static string MissingDTDSummary {
            get {
                return ResourceManager.GetString("MissingDTDSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DTD found for {0}.
        /// </summary>
        public static string NoDTDFound {
            get {
                return ResourceManager.GetString("NoDTDFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No element definition found for {0}.
        /// </summary>
        public static string NoElementDefinitionFound {
            get {
                return ResourceManager.GetString("NoElementDefinitionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following are permitted as children for &lt;{0}&gt;:.
        /// </summary>
        public static string PermittedChildren {
            get {
                return ResourceManager.GetString("PermittedChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined element.
        /// </summary>
        public static string UndefinedElement {
            get {
                return ResourceManager.GetString("UndefinedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined element
        ///An element definition was not found for:
        ///{0}.
        /// </summary>
        public static string UndefinedElementSummary {
            get {
                return ResourceManager.GetString("UndefinedElementSummary", resourceCulture);
            }
        }
    }
}
