//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tobi_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tobi_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobi.Tobi.Lang", typeof(Tobi_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string Copy_ {
            get {
                return ResourceManager.GetString("Copy_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_ut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut to clipboard.
        /// </summary>
        public static string Cut_ {
            get {
                return ResourceManager.GetString("Cut_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit Tobi ?.
        /// </summary>
        public static string ExitConfirm {
            get {
                return ResourceManager.GetString("ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get help.
        /// </summary>
        public static string Help_ {
            get {
                return ResourceManager.GetString("Help_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string LangStringKey1 {
            get {
                return ResourceManager.GetString("LangStringKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Keyboard shortcuts.
        /// </summary>
        public static string ManageShortcuts {
            get {
                return ResourceManager.GetString("ManageShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View keyboard shortcuts.
        /// </summary>
        public static string ManageShortcuts_ {
            get {
                return ResourceManager.GetString("ManageShortcuts_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        public static string Menu_Exit_ {
            get {
                return ResourceManager.GetString("Menu_Exit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Find.
        /// </summary>
        public static string Menu_Find {
            get {
                return ResourceManager.GetString("Menu_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no document.
        /// </summary>
        public static string NoDocument {
            get {
                return ResourceManager.GetString("NoDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse application folder.
        /// </summary>
        public static string OpenTobiFolder {
            get {
                return ResourceManager.GetString("OpenTobiFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a file browser where the Tobi.exe application is run from (and where Tobi.log resides)..
        /// </summary>
        public static string OpenTobiFolder_ {
            get {
                return ResourceManager.GetString("OpenTobiFolder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse system storage folder.
        /// </summary>
        public static string OpenTobiIsolatedStorage {
            get {
                return ResourceManager.GetString("OpenTobiIsolatedStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a file browser where Tobi&apos;s system files are located..
        /// </summary>
        public static string OpenTobiIsolatedStorage_ {
            get {
                return ResourceManager.GetString("OpenTobiIsolatedStorage_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse settings folder.
        /// </summary>
        public static string OpenTobiSettingsFolder {
            get {
                return ResourceManager.GetString("OpenTobiSettingsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a file browser where the Tobi user settings are stored..
        /// </summary>
        public static string OpenTobiSettingsFolder_ {
            get {
                return ResourceManager.GetString("OpenTobiSettingsFolder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from clipboard.
        /// </summary>
        public static string Paste_ {
            get {
                return ResourceManager.GetString("Paste_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG: _Where is [&quot; + LOG_FILE_NAME + &quot;] ?.
        /// </summary>
        public static string ShowLogFilePath {
            get {
                return ResourceManager.GetString("ShowLogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the path to the Tobi log file.\nYou may copy/paste into the file explorer\nand open with any text editor..
        /// </summary>
        public static string ShowLogFilePath_ {
            get {
                return ResourceManager.GetString("ShowLogFilePath_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Decrease magnification.
        /// </summary>
        public static string UI_DecreaseMagnification {
            get {
                return ResourceManager.GetString("UI_DecreaseMagnification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease the UI magnification level.
        /// </summary>
        public static string UI_DecreaseMagnification_ {
            get {
                return ResourceManager.GetString("UI_DecreaseMagnification_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Increase magnification.
        /// </summary>
        public static string UI_IncreaseMagnification {
            get {
                return ResourceManager.GetString("UI_IncreaseMagnification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the UI magnification level.
        /// </summary>
        public static string UI_IncreaseMagnification_ {
            get {
                return ResourceManager.GetString("UI_IncreaseMagnification_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset magnification.
        /// </summary>
        public static string UI_ResetMagnification {
            get {
                return ResourceManager.GetString("UI_ResetMagnification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the UI magnification level.
        /// </summary>
        public static string UI_ResetMagnification_ {
            get {
                return ResourceManager.GetString("UI_ResetMagnification_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected problem !.
        /// </summary>
        public static string Unexpected {
            get {
                return ResourceManager.GetString("Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobi {{{0}}} - Please wait....
        /// </summary>
        public static string WindowsTitleKey {
            get {
                return ResourceManager.GetString("WindowsTitleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobi {{{0}}} {1}[{2}].
        /// </summary>
        public static string WindowsTitleKey2 {
            get {
                return ResourceManager.GetString("WindowsTitleKey2", resourceCulture);
            }
        }
    }
}
