//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Common {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings_KeyGesture : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_KeyGesture defaultInstance = ((Settings_KeyGesture)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_KeyGesture())));
        
        public static Settings_KeyGesture Default {
            get {
                return defaultInstance;
            }
        }
    }
}
