//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.Urakawa {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableAutoSave {
            get {
                return ((bool)(this["EnableAutoSave"]));
            }
            set {
                this["EnableAutoSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRecentFilesMenu {
            get {
                return ((bool)(this["EnableRecentFilesMenu"]));
            }
            set {
                this["EnableRecentFilesMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportIncludeImageDescriptions {
            get {
                return ((bool)(this["ExportIncludeImageDescriptions"]));
            }
            set {
                this["ExportIncludeImageDescriptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AudioCodecDisableACM {
            get {
                return ((bool)(this["AudioCodecDisableACM"]));
            }
            set {
                this["AudioCodecDisableACM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AudioExportEncodeToMp3 {
            get {
                return ((bool)(this["AudioExportEncodeToMp3"]));
            }
            set {
                this["AudioExportEncodeToMp3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kbps_64")]
        public global::AudioLib.Mp3BitRate AudioExportMp3Bitrate {
            get {
                return ((global::AudioLib.Mp3BitRate)(this["AudioExportMp3Bitrate"]));
            }
            set {
                this["AudioExportMp3Bitrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hz44100")]
        public global::AudioLib.SampleRate AudioExportSampleRate {
            get {
                return ((global::AudioLib.SampleRate)(this["AudioExportSampleRate"]));
            }
            set {
                this["AudioExportSampleRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AudioExportStereo {
            get {
                return ((bool)(this["AudioExportStereo"]));
            }
            set {
                this["AudioExportStereo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hz44100")]
        public global::AudioLib.SampleRate AudioProjectSampleRate {
            get {
                return ((global::AudioLib.SampleRate)(this["AudioProjectSampleRate"]));
            }
            set {
                this["AudioProjectSampleRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AudioProjectStereo {
            get {
                return ((bool)(this["AudioProjectStereo"]));
            }
            set {
                this["AudioProjectStereo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XUK_PrettyFormat {
            get {
                return ((bool)(this["XUK_PrettyFormat"]));
            }
            set {
                this["XUK_PrettyFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pagenum,linenum,sidebar,footnote,endnote,rearnote,prodnote,annotation,annoref,not" +
            "e,noteref,")]
        public string Skippables {
            get {
                return ((string)(this["Skippables"]));
            }
            set {
                this["Skippables"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("background-color: #FF0000; color: white; font-weight: bold;")]
        public string MediaOverlayActiveCSS {
            get {
                return ((string)(this["MediaOverlayActiveCSS"]));
            }
            set {
                this["MediaOverlayActiveCSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\daisy-pipeline\\cli\\dp2.exe")]
        public string Pipeline_ExePath {
            get {
                return ((string)(this["Pipeline_ExePath"]));
            }
            set {
                this["Pipeline_ExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dtbook-to-html")]
        public string Pipeline_Script {
            get {
                return ((string)(this["Pipeline_Script"]));
            }
            set {
                this["Pipeline_Script"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double ProcessTimeout_Minutes {
            get {
                return ((double)(this["ProcessTimeout_Minutes"]));
            }
            set {
                this["ProcessTimeout_Minutes"] = value;
            }
        }
    }
}
