//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.Urakawa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tobi_Plugin_Urakawa_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tobi_Plugin_Urakawa_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobi.Plugin.Urakawa.Tobi.Plugin.Urakawa.Lang", typeof(Tobi_Plugin_Urakawa_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file..
        /// </summary>
        public static string CannotOpenLocalFile {
            get {
                return ResourceManager.GetString("CannotOpenLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open file!.
        /// </summary>
        public static string CannotOpenLocalFile_ {
            get {
                return ResourceManager.GetString("CannotOpenLocalFile_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up data files....
        /// </summary>
        public static string CleaningUpDataFiles {
            get {
                return ResourceManager.GetString("CleaningUpDataFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close document.
        /// </summary>
        public static string Close_ {
            get {
                return ResourceManager.GetString("Close_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying data files....
        /// </summary>
        public static string CopyingDataFiles {
            get {
                return ResourceManager.GetString("CopyingDataFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cleanup unused data.
        /// </summary>
        public static string DataCleanup {
            get {
                return ResourceManager.GetString("DataCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove files unused by the document.
        /// </summary>
        public static string DataCleanup_ {
            get {
                return ResourceManager.GetString("DataCleanup_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the current document  to DAISY....
        /// </summary>
        public static string Export_ {
            get {
                return ResourceManager.GetString("Export_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        public static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing....
        /// </summary>
        public static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear.
        /// </summary>
        public static string Menu_ClearRecentFiles {
            get {
                return ResourceManager.GetString("Menu_ClearRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the list of recently-opened files..
        /// </summary>
        public static string Menu_ClearRecentFiles_ {
            get {
                return ResourceManager.GetString("Menu_ClearRecentFiles_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open / import.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or import a document.
        /// </summary>
        public static string Open_ {
            get {
                return ResourceManager.GetString("Open_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current document.
        /// </summary>
        public static string OpenDocumentFolder {
            get {
                return ResourceManager.GetString("OpenDocumentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a file browser where the currently-loaded document is located..
        /// </summary>
        public static string OpenDocumentFolder_ {
            get {
                return ResourceManager.GetString("OpenDocumentFolder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open the saved document ?.
        /// </summary>
        public static string OpenSaveAsQuestion {
            get {
                return ResourceManager.GetString("OpenSaveAsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open saved document ?.
        /// </summary>
        public static string OpenSaveAsQuestion_ {
            get {
                return ResourceManager.GetString("OpenSaveAsQuestion_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Overwrite.
        /// </summary>
        public static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to overwrite a file.
        ///Do you want to continue ?.
        /// </summary>
        public static string OverwriteConfirm_File {
            get {
                return ResourceManager.GetString("OverwriteConfirm_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to overwrite a folder.
        ///Do you want to continue ?.
        /// </summary>
        public static string OverwriteConfirm_Folder {
            get {
                return ResourceManager.GetString("OverwriteConfirm_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo last undone action.
        /// </summary>
        public static string Redo_ {
            get {
                return ResourceManager.GetString("Redo_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string RunningTask {
            get {
                return ResourceManager.GetString("RunningTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current document.
        /// </summary>
        public static string Save_ {
            get {
                return ResourceManager.GetString("Save_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ave as....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current document as....
        /// </summary>
        public static string SaveAs_ {
            get {
                return ResourceManager.GetString("SaveAs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved..
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo last action.
        /// </summary>
        public static string Undo_ {
            get {
                return ResourceManager.GetString("Undo_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save before close.
        /// </summary>
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes.
        ///Agree to save the document now ?.
        /// </summary>
        public static string UnsavedChangesConfirm {
            get {
                return ResourceManager.GetString("UnsavedChangesConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you close the document without saving,
        ///any changes will be lost !.
        /// </summary>
        public static string UnsavedChangesDetails {
            get {
                return ResourceManager.GetString("UnsavedChangesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the XML content of the XUK file....
        /// </summary>
        public static string UrakawaOpenAction_LongDesc {
            get {
                return ResourceManager.GetString("UrakawaOpenAction_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening XUK file....
        /// </summary>
        public static string UrakawaOpenAction_ShortDesc {
            get {
                return ResourceManager.GetString("UrakawaOpenAction_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A context for opening and saving the data model of a Urakawa SDK project..
        /// </summary>
        public static string UrakawaPlugin_Description {
            get {
                return ResourceManager.GetString("UrakawaPlugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urakawa SDK session manager..
        /// </summary>
        public static string UrakawaPlugin_Name {
            get {
                return ResourceManager.GetString("UrakawaPlugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving the document as XML into the XUK file....
        /// </summary>
        public static string UrakawaSaveAction_LongDesc {
            get {
                return ResourceManager.GetString("UrakawaSaveAction_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving XUK file....
        /// </summary>
        public static string UrakawaSaveAction_ShortDesc {
            get {
                return ResourceManager.GetString("UrakawaSaveAction_ShortDesc", resourceCulture);
            }
        }
    }
}
