//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Common {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings_KeyGesture : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_KeyGesture defaultInstance = ((Settings_KeyGesture)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_KeyGesture())));
        
        public static Settings_KeyGesture Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] D")]
        public global::Tobi.Common.UI.KeyGestureString Keyboard_DialogExpand {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["Keyboard_DialogExpand"]));
            }
            set {
                this["Keyboard_DialogExpand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] D")]
        public global::Tobi.Common.UI.KeyGestureString Keyboard_DialogCollapse {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["Keyboard_DialogCollapse"]));
            }
            set {
                this["Keyboard_DialogCollapse"] = value;
            }
        }
    }
}
