//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tobi_Common_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tobi_Common_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobi.Common.Tobi.Common.Lang", typeof(Tobi_Common_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string CloseDialog {
            get {
                return ResourceManager.GetString("CloseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hide details.
        /// </summary>
        public static string DetailsCollapse {
            get {
                return ResourceManager.GetString("DetailsCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide detailed information.
        /// </summary>
        public static string DetailsCollapse_ {
            get {
                return ResourceManager.GetString("DetailsCollapse_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show details.
        /// </summary>
        public static string DetailsExpand {
            get {
                return ResourceManager.GetString("DetailsExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display detailed information.
        /// </summary>
        public static string DetailsExpand_ {
            get {
                return ResourceManager.GetString("DetailsExpand_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Audio.
        /// </summary>
        public static string Menu_Audio {
            get {
                return ResourceManager.GetString("Menu_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Playback.
        /// </summary>
        public static string Menu_AudioPlayback {
            get {
                return ResourceManager.GetString("Menu_AudioPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recording.
        /// </summary>
        public static string Menu_AudioRecording {
            get {
                return ResourceManager.GetString("Menu_AudioRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Selection.
        /// </summary>
        public static string Menu_AudioSelection {
            get {
                return ResourceManager.GetString("Menu_AudioSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Navigation.
        /// </summary>
        public static string Menu_AudioTransport {
            get {
                return ResourceManager.GetString("Menu_AudioTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zoom.
        /// </summary>
        public static string Menu_AudioZoom {
            get {
                return ResourceManager.GetString("Menu_AudioZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Focus.
        /// </summary>
        public static string Menu_Focus {
            get {
                return ResourceManager.GetString("Menu_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma_gnification.
        /// </summary>
        public static string Menu_Magnification {
            get {
                return ResourceManager.GetString("Menu_Magnification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navi_gation.
        /// </summary>
        public static string Menu_Navigation {
            get {
                return ResourceManager.GetString("Menu_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open recent.
        /// </summary>
        public static string Menu_OpenRecent {
            get {
                return ResourceManager.GetString("Menu_OpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Structure.
        /// </summary>
        public static string Menu_Structure {
            get {
                return ResourceManager.GetString("Menu_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _System.
        /// </summary>
        public static string Menu_System {
            get {
                return ResourceManager.GetString("Menu_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected problem !.
        /// </summary>
        public static string Unexpected {
            get {
                return ResourceManager.GetString("Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
