//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.AudioPane {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings_KeyGestures : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_KeyGestures defaultInstance = ((Settings_KeyGestures)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_KeyGestures())));
        
        public static Settings_KeyGestures Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F7")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_Focus {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_Focus"]));
            }
            set {
                this["KeyGesture_Audio_Focus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F4")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_FocusStatusBar {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_FocusStatusBar"]));
            }
            set {
                this["KeyGesture_Audio_FocusStatusBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] OemOpenBrackets")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_BeginSelection {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_BeginSelection"]));
            }
            set {
                this["KeyGesture_Audio_BeginSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] OemCloseBrackets")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_EndSelection {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_EndSelection"]));
            }
            set {
                this["KeyGesture_Audio_EndSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] Back")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_Delete {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_Delete"]));
            }
            set {
                this["KeyGesture_Audio_Delete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL | ALT | SHIFT ] O")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_InsertFile {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_InsertFile"]));
            }
            set {
                this["KeyGesture_Audio_InsertFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[CTRL|SHIFT] O")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_OpenFile {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_OpenFile"]));
            }
            set {
                this["KeyGesture_Audio_OpenFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL | SHIFT | ALT ] K")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_GotoBegin {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_GotoBegin"]));
            }
            set {
                this["KeyGesture_Audio_GotoBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL | SHIFT | ALT ] L")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_GotoEnd {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_GotoEnd"]));
            }
            set {
                this["KeyGesture_Audio_GotoEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL | SHIFT ] [")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_SelectPreviousChunk {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_SelectPreviousChunk"]));
            }
            set {
                this["KeyGesture_Audio_SelectPreviousChunk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL | SHIFT ] ]")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_SelectNextChunk {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_SelectNextChunk"]));
            }
            set {
                this["KeyGesture_Audio_SelectNextChunk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL | SHIFT ] K")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_StepBack {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_StepBack"]));
            }
            set {
                this["KeyGesture_Audio_StepBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL | SHIFT ] L")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_StepForward {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_StepForward"]));
            }
            set {
                this["KeyGesture_Audio_StepForward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] L")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_FastForward {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_FastForward"]));
            }
            set {
                this["KeyGesture_Audio_FastForward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] K")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_Rewind {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_Rewind"]));
            }
            set {
                this["KeyGesture_Audio_Rewind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] D")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_ClearSelection {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_ClearSelection"]));
            }
            set {
                this["KeyGesture_Audio_ClearSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] W")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_ZoomSelection {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_ZoomSelection"]));
            }
            set {
                this["KeyGesture_Audio_ZoomSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL | SHIFT ] W")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_FitFull {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_FitFull"]));
            }
            set {
                this["KeyGesture_Audio_FitFull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] G")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_AutoPlay {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_AutoPlay"]));
            }
            set {
                this["KeyGesture_Audio_AutoPlay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] R")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_StartRecord {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_StartRecord"]));
            }
            set {
                this["KeyGesture_Audio_StartRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] R")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_StopRecord {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_StopRecord"]));
            }
            set {
                this["KeyGesture_Audio_StopRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] M")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_StartMonitor {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_StartMonitor"]));
            }
            set {
                this["KeyGesture_Audio_StartMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] M")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_StopMonitor {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_StopMonitor"]));
            }
            set {
                this["KeyGesture_Audio_StopMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] P")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_Play {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_Play"]));
            }
            set {
                this["KeyGesture_Audio_Play"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL | SHIFT ] P")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_PlayPreviewLeft {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_PlayPreviewLeft"]));
            }
            set {
                this["KeyGesture_Audio_PlayPreviewLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL | SHIFT | ALT ] P")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_PlayPreviewRight {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_PlayPreviewRight"]));
            }
            set {
                this["KeyGesture_Audio_PlayPreviewRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] P")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_Pause {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_Pause"]));
            }
            set {
                this["KeyGesture_Audio_Pause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL | SHIFT | ALT ] O")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_ShowOptions {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_ShowOptions"]));
            }
            set {
                this["KeyGesture_Audio_ShowOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] A")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Audio_SelectAll {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Audio_SelectAll"]));
            }
            set {
                this["KeyGesture_Audio_SelectAll"] = value;
            }
        }
    }
}
