//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.AudioPane {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings_KeyGestures : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_KeyGestures defaultInstance = ((Settings_KeyGestures)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_KeyGestures())));
        
        public static Settings_KeyGestures Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Focus {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Focus"]));
            }
            set {
                this["KeyGesture_Focus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_FocusStatusBar {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_FocusStatusBar"]));
            }
            set {
                this["KeyGesture_FocusStatusBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_BeginSelection {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_BeginSelection"]));
            }
            set {
                this["KeyGesture_BeginSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_EndSelection {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_EndSelection"]));
            }
            set {
                this["KeyGesture_EndSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Delete {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Delete"]));
            }
            set {
                this["KeyGesture_Delete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_InsertFile {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_InsertFile"]));
            }
            set {
                this["KeyGesture_InsertFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_OpenFile {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_OpenFile"]));
            }
            set {
                this["KeyGesture_OpenFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_GotoBegin {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_GotoBegin"]));
            }
            set {
                this["KeyGesture_GotoBegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_GotoEnd {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_GotoEnd"]));
            }
            set {
                this["KeyGesture_GotoEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_SelectPreviousChunk {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_SelectPreviousChunk"]));
            }
            set {
                this["KeyGesture_SelectPreviousChunk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_SelectNextChunk {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_SelectNextChunk"]));
            }
            set {
                this["KeyGesture_SelectNextChunk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_StepBack {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_StepBack"]));
            }
            set {
                this["KeyGesture_StepBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_StepForward {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_StepForward"]));
            }
            set {
                this["KeyGesture_StepForward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_FastForward {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_FastForward"]));
            }
            set {
                this["KeyGesture_FastForward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Rewind {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Rewind"]));
            }
            set {
                this["KeyGesture_Rewind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_ClearSelection {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_ClearSelection"]));
            }
            set {
                this["KeyGesture_ClearSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_ZoomSelection {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_ZoomSelection"]));
            }
            set {
                this["KeyGesture_ZoomSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_FitFull {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_FitFull"]));
            }
            set {
                this["KeyGesture_FitFull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_AutoPlay {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_AutoPlay"]));
            }
            set {
                this["KeyGesture_AutoPlay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_StartRecord {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_StartRecord"]));
            }
            set {
                this["KeyGesture_StartRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_StopRecord {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_StopRecord"]));
            }
            set {
                this["KeyGesture_StopRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_StartMonitor {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_StartMonitor"]));
            }
            set {
                this["KeyGesture_StartMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_StopMonitor {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_StopMonitor"]));
            }
            set {
                this["KeyGesture_StopMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Play {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Play"]));
            }
            set {
                this["KeyGesture_Play"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_PlayPreviewLeft {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_PlayPreviewLeft"]));
            }
            set {
                this["KeyGesture_PlayPreviewLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_PlayPreviewRight {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_PlayPreviewRight"]));
            }
            set {
                this["KeyGesture_PlayPreviewRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Pause {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Pause"]));
            }
            set {
                this["KeyGesture_Pause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_ShowOptions {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_ShowOptions"]));
            }
            set {
                this["KeyGesture_ShowOptions"] = value;
            }
        }
    }
}
