//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.Validator.ContentDocument {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tobi_Plugin_Validator_ContentDocument_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tobi_Plugin_Validator_ContentDocument_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobi.Plugin.Validator.ContentDocument.Tobi.Plugin.Validator.ContentDocument.Lang", typeof(Tobi_Plugin_Validator_ContentDocument_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A validator that uses data from a DTD to validate elements in a document tree..
        /// </summary>
        public static string AValidatorThatUsesDataFromADTDToValidateElementsInADocumentTree {
            get {
                return ResourceManager.GetString("AValidatorThatUsesDataFromADTDToValidateElementsInADocumentTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Document Validator..
        /// </summary>
        public static string ContentDocumentValidator {
            get {
                return ResourceManager.GetString("ContentDocumentValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Document Validator.
        /// </summary>
        public static string ContentDocumentValidator_Key {
            get {
                return ResourceManager.GetString("ContentDocumentValidator_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document structure error.
        /// </summary>
        public static string DocStructureError {
            get {
                return ResourceManager.GetString("DocStructureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General document error.
        /// </summary>
        public static string GeneralDocumentError {
            get {
                return ResourceManager.GetString("GeneralDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element {0} contains an invalid sequence of child elements.
        /// </summary>
        public static string InvalidSequence {
            get {
                return ResourceManager.GetString("InvalidSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing DTD.
        /// </summary>
        public static string MissingDTD {
            get {
                return ResourceManager.GetString("MissingDTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DTD found for {0}.
        /// </summary>
        public static string NoDTDFound {
            get {
                return ResourceManager.GetString("NoDTDFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No element definition found for {0}.
        /// </summary>
        public static string NoElementDefinitionFound {
            get {
                return ResourceManager.GetString("NoElementDefinitionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , starting with {0}..
        /// </summary>
        public static string StartingWith0 {
            get {
                return ResourceManager.GetString("StartingWith0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined element.
        /// </summary>
        public static string UndefinedElement {
            get {
                return ResourceManager.GetString("UndefinedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error.
        /// </summary>
        public static string UnspecifiedError {
            get {
                return ResourceManager.GetString("UnspecifiedError", resourceCulture);
            }
        }
    }
}
