//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.Urakawa {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings_KeyGestures : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_KeyGestures defaultInstance = ((Settings_KeyGestures)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_KeyGestures())));
        
        public static Settings_KeyGestures Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] O")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Urakawa_Open {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Urakawa_Open"]));
            }
            set {
                this["KeyGesture_Urakawa_Open"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] W")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Urakawa_Close {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Urakawa_Close"]));
            }
            set {
                this["KeyGesture_Urakawa_Close"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ]  Z")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Urakawa_Undo {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Urakawa_Undo"]));
            }
            set {
                this["KeyGesture_Urakawa_Undo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL   | SHIFT ]  Z")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Urakawa_Redo {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Urakawa_Redo"]));
            }
            set {
                this["KeyGesture_Urakawa_Redo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL ] S")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Urakawa_Save {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Urakawa_Save"]));
            }
            set {
                this["KeyGesture_Urakawa_Save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ CTRL | SHIFT  |  ALT ] S")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Urakawa_Export {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Urakawa_Export"]));
            }
            set {
                this["KeyGesture_Urakawa_Export"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ SHIFT  | CTRL ] S")]
        public global::Tobi.Common.UI.KeyGestureString KeyGesture_Urakawa_SaveAs {
            get {
                return ((global::Tobi.Common.UI.KeyGestureString)(this["KeyGesture_Urakawa_SaveAs"]));
            }
            set {
                this["KeyGesture_Urakawa_SaveAs"] = value;
            }
        }
    }
}
