//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobi.Plugin.Validator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tobi_Plugin_Validator_Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tobi_Plugin_Validator_Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tobi.Plugin.Validator.Tobi.Plugin.Validator.Lang", typeof(Tobi_Plugin_Validator_Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of {0} report.
        ///    
        ///    .
        /// </summary>
        public static string ClipboardEndOfValidatorReport {
            get {
                return ResourceManager.GetString("ClipboardEndOfValidatorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}. {2}
        ///    
        ///    .
        /// </summary>
        public static string ClipboardErrorEntry {
            get {
                return ResourceManager.GetString("ClipboardErrorEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all validation errors
        ///    
        ///    .
        /// </summary>
        public static string ClipboardListOfAll {
            get {
                return ResourceManager.GetString("ClipboardListOfAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors reported
        ///    
        ///    .
        /// </summary>
        public static string ClipboardNoErrors {
            get {
                return ResourceManager.GetString("ClipboardNoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total errors: {0}
        ///    .
        /// </summary>
        public static string ClipboardTotalErrorCount {
            get {
                return ResourceManager.GetString("ClipboardTotalErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1}: {2}
        ///    
        ///    .
        /// </summary>
        public static string ClipboardValidatorEntry {
            get {
                return ResourceManager.GetString("ClipboardValidatorEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the validation dialog.
        /// </summary>
        public static string CmdValidationCheck_LongDesc {
            get {
                return ResourceManager.GetString("CmdValidationCheck_LongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation dialog....
        /// </summary>
        public static string CmdValidationCheck_ShortDesc {
            get {
                return ResourceManager.GetString("CmdValidationCheck_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents copied to clipboard..
        /// </summary>
        public static string ContentsCopied {
            get {
                return ResourceManager.GetString("ContentsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all error details to clipboard.
        /// </summary>
        public static string CopyAllLink {
            get {
                return ResourceManager.GetString("CopyAllLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy details to clipboard.
        /// </summary>
        public static string CopyLink {
            get {
                return ResourceManager.GetString("CopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A framework to validate the data model of an authored Urakawa SDK project..
        /// </summary>
        public static string ValidatorPlugin_Description {
            get {
                return ResourceManager.GetString("ValidatorPlugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Validator..
        /// </summary>
        public static string ValidatorPlugin_Name {
            get {
                return ResourceManager.GetString("ValidatorPlugin_Name", resourceCulture);
            }
        }
    }
}
